//
//  LocalizedStrings.swift
//  Inspec
//
//  Created by Justin Cook on 10/29/22.
//

import Foundation
import SwiftUI

/// Note: If a new string is added to the localization file(s) please update these enums accordingly
enum LocalizedStrings: String, CaseIterable {
    case APP_NAME,
         TABBAR_BUTTON_HOME,
         TABBAR_BUTTON_WALLET,
         TABBAR_BUTTON_SETTINGS,
         TABBAR_BUTTON_ALERTS,
         NAVIGATION_BUTTON_SKIP,
         ONBOARDING_PAGE_1_TITLE,
         ONBOARDING_PAGE_2_TITLE,
         ONBOARDING_PAGE_3_TITLE,
         ONBOARDING_PAGE_3_CTA,
         TOS,
         PP,
         OR_FORK_PROMPT,
         CONTINUE,
         SEARCH,
         DISMISS,
         DONE,
         NO_SEARCH_RESULTS,
         CANCEL,
         ABSENCE_OF_VALUE,
         SHOW_ALL,
         QUICK_EDIT,
         MINIMIZE,
         MAXIMIZE,
         PREDICTION,
         TIMELINE,
         PERFORMANCE,
         COVER_SCREEN_TITLE_WELCOME_BACK,
         COVER_SCREEN_TITLE_WELCOME_BACK_NEWLINE,
         GET_STARTED_SCREEN_CURATE_BUTTON,
         GET_STARTED_SCREEN_AUTO_GEN_BUTTON,
         GET_STARTED_SCREEN_GET_STARTED_PROMPT,
         GET_STARTED_SCREEN_LEARN_MORE_BUTTON,
         PORTFOLIO_CURATION_SCREEN_TITLE_FTUE_NEWLINE,
         PORTFOLIO_CURATION_SCREEN_TITLE_FTUE,
         PORTFOLIO_CURATION_SCREEN_TITLE,
         PORTFOLIO_CURATION_SCREEN_SEARCHBAR_PLACEHOLDER,
         PORTFOLIO_CURATION_SCREEN_SYMBOL_HEADER,
         PORTFOLIO_CURATION_SCREEN_RANK,
         PORTFOLIO_CURATION_SCREEN_VOLUME_HEADER,
         PORTFOLIO_CURATION_SCREEN_ASSET_ID_HEADER,
         PORTFOLIO_CURATION_SCREEN_ASSET_NAME_HEADER,
         PORTFOLIO_CURATION_SCREEN_PRICE_HEADER,
         PORTFOLIO_CURATION_SCREEN_CURRENCY_PREFERENCES_BUTTON,
         PORTFOLIO_CURATION_SCREEN_LANGUAGE_PREFERENCES_BUTTON,
         PORTFOLIO_CURATION_SCREEN_MAKE_CHANGES_LATER_PROMPT,
         PORTFOLIO_CURATION_SCREEN_SEARCH_RESULT_COUNT_SINGULAR,
         PORTFOLIO_CURATION_SCREEN_SEARCH_RESULT_COUNT_PLURAL,
         PORTFOLIO_CURATION_SCREEN_SEARCH_RESULT_COUNT_NONE,
         PORTFOLIO_CURATION_SCREEN_NO_SEARCH_RESULTS_NEWLINE,
         PORTFOLIO_CURATION_SCREEN_NO_SEARCH_RESULTS,
         PORTFOLIO_CURATION_SCREEN_PORTFOLIO_COIN_COUNT_SINGULAR,
         PORTFOLIO_CURATION_SCREEN_PORTFOLIO_COIN_COUNT_PLURAL,
         AUTH_SCREEN_TITLE_RESET_PASSCODE,
         AUTH_SCREEN_TITLE_RESET_PASSCODE_NEWLINE,
         AUTH_SCREEN_TITLE_SET_PASSCODE,
         AUTH_SCREEN_TITLE_SET_PASSCODE_NEWLINE,
         AUTH_SCREEN_TITLE_INCORRECT_PASSCODE,
         AUTH_SCREEN_TITLE_INCORRECT_PASSCODE_NEWLINE,
         AUTH_SCREEN_TITLE_PASSCODE_CONFIRMATION,
         AUTH_SCREEN_TITLE_PASSCODE_CONFIRMATION_NEWLINE,
         AUTH_SCREEN_TITLE_CONTINUE_WITH_PASSCODE,
         AUTH_SCREEN_TITLE_CONTINUE_WITH_PASSCODE_NEWLINE,
         AUTH_SCREEN_TITLE_CONTINUE_WITH_FACEID,
         AUTH_SCREEN_TITLE_CONTINUE_WITH_FACEID_NEWLINE,
         AUTH_SCREEN_TITLE_AUTHENTICATION_SUCCESSFUL,
         AUTH_SCREEN_TITLE_AUTHENTICATION_SUCCESSFUL_NEWLINE,
         AUTH_SCREEN_TITLE_COOL_DOWN,
         AUTH_SCREEN_TITLE_COOL_DOWN_NEWLINE,
         AUTH_SCREEN_BOTTOM_CTA_FORGOT_PASSCODE,
         AUTH_SCREEN_ATTEMPTS_REMAINING_COUNTER_SINGULAR,
         AUTH_SCREEN_ATTEMPTS_REMAINING_COUNTER_PLURAL,
         AUTH_SCREEN_RETRY_TIME_REMAINING_COUNTER,
         HOME_SCREEN_GREETING_NEW_USER_1,
         HOME_SCREEN_GREETING_NEW_USER_2,
         HOME_SCREEN_GREETING_NEW_USER_3,
         HOME_SCREEN_GREETING_RETURNING_USER_1,
         HOME_SCREEN_GREETING_RETURNING_USER_2,
         HOME_SCREEN_GREETING_RETURNING_USER_3,
         HOME_SCREEN_GREETING_RETURNING_USER_4,
         HOME_SCREEN_SECTION_TITLE_MY_PORTFOLIO,
         HOME_SCREEN_SECTION_MY_PORTFOLIO_PLACEHOLDER_BUTTON_TITLE,
         HOME_SCREEN_SECTION_TITLE_ALL_ASSETS,
         HOME_SCREEN_SECTION_TITLE_DAILY_HIGHS,
         HOME_SCREEN_SECTION_TITLE_DAILY_LOWS,
         HOME_SCREEN_SECTION_TITLE_MARKET_PREDICTIONS,
         HOME_SCREEN_SECTION_TITLE_CRYPTO_NEWS,
         BANNER_EVENT_FTUE_WELCOME_MESSAGE_CTA,
         WALLET_SCREEN_TITLE,
         SETTINGS_SCREEN_TITLE,
         ALERTS_SCREEN_TITLE,
         FUTURE_FEATURE_RELEASE_SCREEN_COMING_SOON,
         FUTURE_FEATURE_RELEASE_SCREEN_MAILING_LIST_SUBSCRIPTION_PROMPT_NOT_SUBSCRIBED,
         FUTURE_FEATURE_RELEASE_SCREEN_MAILING_LIST_SUBSCRIPTION_PROMPT_NOT_SUBSCRIBED_SUBTITLE,
         FUTURE_FEATURE_RELEASE_SCREEN_MAILING_LIST_SUBSCRIPTION_PROMPT_NOT_SUBSCRIBED_SUBTITLE_NEWLINE,
         FUTURE_FEATURE_RELEASE_SCREEN_MAILING_LIST_SUBSCRIPTION_PROMPT_SUBSCRIBED,
         FUTURE_FEATURE_RELEASE_SCREEN_MAILING_LIST_SUBSCRIPTION_PROMPT_SUBSCRIBED_NEWLINE,
         FUTURE_FEATURE_RELEASE_SCREEN_MAILING_LIST_SUBSCRIPTION_PROMPT_SUBSCRIBED_SUBTITLE,
         FUTURE_FEATURE_RELEASE_SCREEN_MAILING_LIST_SUBSCRIPTION_PROMPT_SUBSCRIBED_SUBTITLE_NEWLINE,
         SORT_FILTER_CONTEXT_MENU_TITLE,
         SORT_FILTER_CONTEXT_MENU_NAME_OPTION,
         SORT_FILTER_CONTEXT_MENU_ID_OPTION,
         SORT_FILTER_CONTEXT_MENU_PRICE_OPTION,
         SORT_FILTER_CONTEXT_MENU_RANK_OPTION,
         SORT_FILTER_CONTEXT_MENU_VOLUME_OPTION,
         BOTTOM_SHEET_TITLE_CURRENCY_PREFERENCE,
         BOTTOM_SHEET_TITLE_CURRENCY_PREFERENCE_NEWLINE,
         BOTTOM_SHEET_SEARCHBAR_PLACEHOLDER_CURRENCY_PREFERENCE,
         BOTTOM_SHEET_ADVISORY_CURRENCY_PREFERENCE,
         HUMAN_READABLE_INTERNET_NOT_AVAILABLE,
         HUMAN_READABLE_INTERNET_CELLULAR_DENIED,
         HUMAN_READABLE_INTERNET_WIFI_DENIED,
         HUMAN_READABLE_INTERNET_LOCAL_NETWORK_DENIED
}

extension LocalizedStrings {
    /// String keys for SwiftUI and compiler time localization
    static func getLocalizedStringKey(for key: LocalizedStrings) -> LocalizedStringKey {
        
        return LocalizedStringKey(key.rawValue)
    }
    
    /// Strings for UIKit and manual localization
    static func getLocalizedString(for string: LocalizedStrings) -> String {
        return string.rawValue.localized
    }
}

